### ISSUE TITLE
Split into modules

### ISSUE THREAD

**Issue by ghost** [midzer/tobii#1]

**Comment by viliusle** [comment]
Step 1  - https://github.com/viliusle/tobii/commit/57c100f95de01b2ba8dad69cda0799a2ae206459
Looks like everything works fine.

**Comment by viliusle** [comment]
Code split complete. Please review https://github.com/viliusle/tobii/tree/develop/src/js/ modifications. Changes:

- all media types logic moved to /types/ folder, separate files. This means editing media type or adding new one will not break any other types. Also index.php was too big, and was using "God" unti-pattern.
- Type detection (`checkSupport`) removed, data-type will be used or it will fall back to "image", simple, but effective.

index.js still looks too big, but I do not see any effective ways to split it even more, since everything is too much related. I tried moving events to events.js, but did not ended well.

p.s. basic features works fine, but there can be some advanced features broken. So more testing will be required until this can go to live.

**Comment by midzer** [comment]
Big Ups for your work, @viliusle 
As there will probably be no breaking change, I'll move it to v2.3.0.
